package com.example.footballapi.modelClasses

data class Matche(
    val Awt: Int? = null,
    val Etm: Etm? = null,
    val Games: GamesX? = null,
    val Shck: Boolean? = null,
    val Tr1ET: String? = null,
    val Tr2ET: String? = null,
    val Trp1: String? = null,
    val Trp2: String? = null,
    val away_score: String? = null,
    val away_score_ht: String? = null,
    val away_score_original: String? = null,
    val away_team: List<HomeTeam>? = null,
    val event_coverage: Int? = null,
    val event_order: Long? = null,
    val event_order_extra: Long? = null,
    val event_priority: Int? = null,
    val event_status_id: Int? = null,
    val event_type: Int? = null,
    val event_winner_type: Int? = null,
    val extra_info: String? = null,
    val home_score: String? = null,
    val home_score_ht: String? = null,
    val home_score_original: String? = null,
    val home_team: List<HomeTeam>? = null,
    val incidents: Incidents? = null,
    val match_id: String? = null,
    val match_status: String? = null,
    val media: Media? = null,
    val provider_id: Int? = null,
    val provider_ids: ProviderIds? = null,
    val seriesInfo: SeriesInfo? = null,
    val sport_id: Int? = null,
    val start_datetime: String? = null,

    var tournamentLogo: String? = null,
    var tournamentName: String? = null
)
