package com.example.footballapi.modelClasses.matchStats

data class MatchDetail(
    val audioCommentary: String,
    val bat: String,
    val coach: String,
    val country: String,
    val detailedStats: String,
    val event: String,
    val exclusivelyOnLsApp: String,
    val `field`: String,
    val gmtTime: String,
    val limitedCoverage: String,
    val limitedCoverageMobile: String,
    val listenToAudioCommentary: String,
    val listenToUnofficialAudioCommentary: String,
    val liveAudioCommentary: String,
    val liveUnofficialAudioCommentary: String,
    val moreInfoLink: String,
    val notStarted: String,
    val overs: String,
    val playInProgress: String,
    val referee: String,
    val team: String,
    val thisMatch: String,
    val toss: String,
    val tvUmpire: String,
    val umpire1: String,
    val umpire2: String,
    val unofficialAudioCommentary: String,
    val venue: String,
    val venueCity: String,
    val venueTime: String,
    val wonTheToss: String
)